version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    environment:
       POSTGRES_ROOT_PASSWORD: password
       POSTGRES_DATABASE: docker
       POSTGRES_USER: docker
       POSTGRES_PASSWORD: docker

  volumes:
    postgres_data:
    postgres_logs: